title: "La data visualisation avec Matplotlib"
logo: img/nny.jpg
description: "L’objectif est de rendre les données lisibles et interprétables visuellement : comparer des valeurs, observer des tendances, repérer des anomalies, illustrer des résultats d’analyses, etc."
show_downloads: true
theme : projet
lang :fr
